--
-- PostgreSQL database load phase
--

CREATE TABLE load_data(
    id SERIAL PRIMARY KEY,
    transaction_id text,
    transaction_status text,
    transaction_cat text default null,
    transaction_desc text default null,
    signed_date date,
    fiscal_year int,
    award_action_type text,
    award_assistance_type text default null,
    award_pricing_type text,
    award_id text,
    award_desc text,
    award_amount numeric,
    award_mod text,
    award_mod_reason text,
    agency_name text,
    agency_office_id text,
    funding_bureau_id text,
    funding_bureau_cat text,
    funding_bureau text,
    fuding_bureau_office_id text,
    recipient_name text,
    recipient_legal_name text,
    recipient_streetaddress text,
    recipient_streetaddress2 text,
    recipient_city text,
    recipient_state text,
    recipient_zip text,
    recipient_country text,
    recipient_cd text,
    recipient_duns text,
    recipient_parent_name text,
    recipient_parent_duns text,
    recipient_phoneno text,
    recipient_faxno text,
    recipient_registration_date date,
    recipient_organization_type text,
    recipient_num_employees int,
    recipient_annual_revenue numeric,
    product_code text,
    product_claimant_code text,
    product_infotechcommercial text,
    product_plafeofmanufacture text,
    geography_city text,
    geography_state text,
    geography_cd text,
    geography_zip text,
    geography_country text,
    last_modified_date date
);

insert into load_data(
	  transaction_id,
    transaction_status,
    transaction_cat,
    transaction_desc,
    signed_date,
    fiscal_year,
    award_action_type,
    award_assistance_type,
    award_pricing_type,
    award_id,
    award_desc,
    award_amount,
    award_mod,
    award_mod_reason,
    agency_name,
    agency_office_id,
    funding_bureau_id,
    funding_bureau_cat,
    funding_bureau,
    fuding_bureau_office_id,
    recipient_name,
    recipient_legal_name,
    recipient_streetaddress,
    recipient_streetaddress2,
    recipient_city,
    recipient_state,
    recipient_zip,
    recipient_country,
    recipient_cd,
    recipient_duns,
    recipient_parent_name,
    recipient_parent_duns,
    recipient_phoneno,
    recipient_faxno,
    recipient_registration_date,
    recipient_organization_type,
    recipient_num_employees,
    recipient_annual_revenue,
    product_code,
    product_claimant_code,
    product_infotechcommercial,
    product_plafeofmanufacture,
    geography_city,
    geography_state,
    geography_cd,
    geography_zip,
    geography_country,
    last_modified_date
)
select
    unique_transaction_id,
    transaction_status,
    'contract',
    'contracts',
    signeddate,
    cast(fiscal_year as int) fiscal_year,
    substring(contractactiontype from 4),
    NULL,
    substring(typeofcontractpricing from 4),
    piid,
    descriptionofcontractrequirement,
    dollarsobligated,
    modnumber,
    substring(reasonformodification from 4),
    substring(maj_agency_cat from 7),
    substring(contractingofficeid from 8),
    substring(agencyid from 7),
    substring(maj_fund_agency_cat from 7),
    substring(contractingofficeagencyid from 7),
    substring(fundingrequetextofficeid from 7),
    vendorname,
    vendorlegalorganizationname,
    streetaddress,
    streetaddress2,
    city,
    state,
    zipcode,
    substring(vendorcountrycode from 6),
    congressionaldistrict,
    dunsnumber,
    mod_parent,
    parentdunsnumber,
    phoneno,
    faxno,
    registrationdate,
    organizationaltype,
    cast(numberofemployees as int) numberofemployees,
    cast(annualrevenue as numeric) annual_revenue,
    substring(productorservicecode from 7),
    claimantprogramcode,
    informationtechnologycommercialitemcategory,
    substring(placeofmanufacture from 3),
    placeofperformancecity,
    substring(pop_state_code from 5),
    substring(placeofperformancecongressionaldistrict from 3),
    placeofperformancezipcode,
    substring(placeofperformancecountrycode from 6),
    last_modified_date
  from
    base_contracts;


insert into load_data(
	  transaction_id,
    transaction_status,
    transaction_cat,
    transaction_desc,
    signed_date,
    fiscal_year,
    award_action_type,
    award_assistance_type,
    award_pricing_type,
    award_id,
    award_desc,
    award_amount,
    award_mod,
    award_mod_reason,
    agency_name,
    agency_office_id,
    funding_bureau_id,
    funding_bureau_cat,
    funding_bureau,
    fuding_bureau_office_id,
    recipient_name,
    recipient_legal_name,
    recipient_streetaddress,
    recipient_streetaddress2,
    recipient_city,
    recipient_state,
    recipient_zip,
    recipient_country,
    recipient_cd,
    recipient_duns,
    recipient_parent_name,
    recipient_parent_duns,
    recipient_phoneno,
    recipient_faxno,
    recipient_registration_date,
    recipient_organization_type,
    recipient_num_employees,
    recipient_annual_revenue,
    product_code,
    product_claimant_code,
    product_infotechcommercial,
    product_plafeofmanufacture,
    geography_city,
    geography_state,
    geography_cd,
    geography_zip,
    geography_country,
    last_modified_date
)
select
    unique_transaction_id,
    transaction_status,
    'grant',
    'grants',
    obligation_action_date,
    cast(fiscal_year as int) fiscal_year,
    substring(action_type from 4),
    substring(assistance_type from 5),
    NULL,
    federal_award_id,
    project_description,
    fed_funding_amount,
    federal_award_mod,
    NULL,
    substring(maj_agency_cat from 7),
    NULL,
    substring(agency_code from 7),
    NULL,
    substring(agency_code from 7),
    NULL,
    recipient_name,
    NULL,
    receip_addr1,
    receip_addr2,
    recipient_city_name,
    principal_place_state,
    recipient_zip,
    recipient_country_code,
    recipient_cd,
    duns_no,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    substring(recip_cat_type from 4),
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    principal_place_cc,
    principal_place_state,
    principal_place_cd,
    principal_place_zip,
    principal_place_country_code,
    last_modified_date
  from
    base_grants;

insert into load_data(
	  transaction_id,
    transaction_status,
    transaction_cat,
    transaction_desc,
    signed_date,
    fiscal_year,
    award_action_type,
    award_assistance_type,
    award_pricing_type,
    award_id,
    award_desc,
    award_amount,
    award_mod,
    award_mod_reason,
    agency_name,
    agency_office_id,
    funding_bureau_id,
    funding_bureau_cat,
    funding_bureau,
    fuding_bureau_office_id,
    recipient_name,
    recipient_legal_name,
    recipient_streetaddress,
    recipient_streetaddress2,
    recipient_city,
    recipient_state,
    recipient_zip,
    recipient_country,
    recipient_cd,
    recipient_duns,
    recipient_parent_name,
    recipient_parent_duns,
    recipient_phoneno,
    recipient_faxno,
    recipient_registration_date,
    recipient_organization_type,
    recipient_num_employees,
    recipient_annual_revenue,
    product_code,
    product_claimant_code,
    product_infotechcommercial,
    product_plafeofmanufacture,
    geography_city,
    geography_state,
    geography_cd,
    geography_zip,
    geography_country,
    last_modified_date
)
select
    unique_transaction_id,
    transaction_status,
    'loan',
    'loans',
    obligation_action_date,
    cast(fiscal_year as int) fiscal_year,
    substring(action_type from 4),
    substring(assistance_type from 5),
    NULL,
    federal_award_id,
    project_description,
    fed_funding_amount,
    federal_award_mod,
    NULL,
    substring(maj_agency_cat from 7),
    NULL,
    substring(agency_code from 7),
    NULL,
    substring(agency_code from 7),
    NULL,
    recipient_name,
    NULL,
    receip_addr1,
    receip_addr2,
    recipient_city_name,
    principal_place_state,
    recipient_zip,
    recipient_country_code,
    recipient_cd,
    duns_no,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    substring(recip_cat_type from 4),
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    principal_place_cc,
    principal_place_state,
    principal_place_cd,
    principal_place_zip,
    principal_place_country_code,
    last_modified_date
  from
    base_loans;


insert into load_data(
	  transaction_id,
    transaction_status,
    transaction_cat,
    transaction_desc,
    signed_date,
    fiscal_year,
    award_action_type,
    award_assistance_type,
    award_pricing_type,
    award_id,
    award_desc,
    award_amount,
    award_mod,
    award_mod_reason,
    agency_name,
    agency_office_id,
    funding_bureau_id,
    funding_bureau_cat,
    funding_bureau,
    fuding_bureau_office_id,
    recipient_name,
    recipient_legal_name,
    recipient_streetaddress,
    recipient_streetaddress2,
    recipient_city,
    recipient_state,
    recipient_zip,
    recipient_country,
    recipient_cd,
    recipient_duns,
    recipient_parent_name,
    recipient_parent_duns,
    recipient_phoneno,
    recipient_faxno,
    recipient_registration_date,
    recipient_organization_type,
    recipient_num_employees,
    recipient_annual_revenue,
    product_code,
    product_claimant_code,
    product_infotechcommercial,
    product_plafeofmanufacture,
    geography_city,
    geography_state,
    geography_cd,
    geography_zip,
    geography_country,
    last_modified_date
)
select
    unique_transaction_id,
    transaction_status,
    'other finance',
    'other financial assistance',
    obligation_action_date,
    cast(fiscal_year as int) fiscal_year,
    substring(action_type from 4),
    substring(assistance_type from 5),
    NULL,
    federal_award_id,
    project_description,
    fed_funding_amount,
    federal_award_mod,
    NULL,
    substring(maj_agency_cat from 7),
    NULL,
    substring(agency_code from 7),
    NULL,
    substring(agency_code from 7),
    NULL,
    recipient_name,
    NULL,
    receip_addr1,
    receip_addr2,
    recipient_city_name,
    principal_place_state,
    recipient_zip,
    recipient_country_code,
    recipient_cd,
    duns_no,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    substring(recip_cat_type from 4),
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    principal_place_cc,
    principal_place_state,
    principal_place_cd,
    principal_place_zip,
    principal_place_country_code,
    last_modified_date
  from
    base_fin;
