--
-- PostgreSQL database for loading sources into staging area
--

--
-- Name base_contracts; TYPE: TABLE; Description: keep track of loaded contracts
--

CREATE TABLE base_contracts (
unique_transaction_id text,
transaction_status text,
dollarsobligated numeric,
baseandexercisedoptionsvalue numeric,
baseandalloptionsvalue numeric,
maj_agency_cat text,
mod_agency text,
maj_fund_agency_cat text,
contractingofficeagencyid text,
contractingofficeid text,
fundingrequetextagencyid text,
fundingrequetextofficeid text,
fundedbyforeignentity text,
signeddate date,
effectivedate date,
currentcompletiondate date,
ultimatecompletiondate date,
lastdatetoorder date,
contractactiontype text,
reasonformodification text,
typeofcontractpricing text,
priceevaluationpercentdifference text,
subcontractplan text,
lettercontract text,
multiyearcontract text,
performancebasedservicecontract text,
majorprogramcode text,
contingencyhumanitarianpeacekeepingoperation text,
contractfinancing text,
costorpricingdata text,
costaccountingstandardsclause text,
descriptionofcontractrequirement text,
purchasecardaspaymentmethod text,
numberofactions int,
nationalinterestactioncode text,
progsourceagency int,
progsourceaccount int,
progsourcesubacct text,
account_title text,
rec_flag boolean,
typeofidc text,
multipleorsingleawardidc text,
programacronym text,
vendorname text,
vendoralternatename text,
vendorlegalorganizationname text,
vendordoingasbusinessname text,
divisionname text,
divisionnumberorofficecode text,
vendorenabled text,
vendorlocationdisableflag text,
ccrexception text,
streetaddress text,
streetaddress2 text,
streetaddress3 text,
city text,
state text,
zipcode text,
vendorcountrycode text,
vendor_state_code text,
vendor_cd text,
congressionaldistrict text,
vendorsitecode text,
vendoralternatesitecode text,
dunsnumber text,
parentdunsnumber text,
phoneno text,
faxno text,
registrationdate date,
renewaldate date,
mod_parent text,
locationcode text,
statecode text,
placeofperformancecity text,
pop_state_code text,
placeofperformancecountrycode text,
placeofperformancezipcode text,
pop_cd text,
placeofperformancecongressionaldistrict text,
psc_cat text,
productorservicecode text,
systemequipmentcode text,
claimantprogramcode text,
principalnaicscode text,
informationtechnologycommercialitemcategory text,
gfe_gfp text,
useofepadesignatedproducts text,
recoveredmaterialclauses text,
seatransportation text,
contractbundling text,
consolidatedcontract text,
countryoforigin text,
placeofmanufacture text,
manufacturingorganizationtype text,
agencyid text,
piid text,
modnumber text,
transactionnumber text,
fiscal_year text,
idvagencyid text,
idvpiid text,
idvmodificationnumber text,
solicitationid text,
extentcompeted text,
reasonnotcompeted text,
numberofoffersreceived text,
commercialitemacquisitionprocedures text,
commercialitemtestprogram text,
smallbusinesscompetitivenessdemonstrationprogram text,
a76action text,
competitiveprocedures text,
solicitationprocedures text,
typeofsetaside text,
localareasetaside text,
evaluatedpreference text,
fedbizopps text,
research text,
statutoryexceptiontofairopportunity text,
organizationaltype text,
numberofemployees text,
annualrevenue text,
firm8aflag boolean,
hubzoneflag boolean,
sdbflag boolean,
issbacertifiedsmalldisadvantagedbusiness boolean,
shelteredworkshopflag boolean,
hbcuflag boolean,
educationalinstitutionflag boolean,
womenownedflag boolean,
veteranownedflag boolean,
srdvobflag boolean,
localgovernmentflag boolean,
minorityinstitutionflag boolean,
aiobflag boolean,
stategovernmentflag boolean,
federalgovernmentflag boolean,
minorityownedbusinessflag boolean,
apaobflag boolean,
tribalgovernmentflag boolean,
baobflag boolean,
naobflag boolean,
saaobflag boolean,
nonprofitorganizationflag boolean,
isothernotforprofitorganization boolean,
isforprofitorganization boolean,
isfoundation boolean,
haobflag boolean,
ishispanicservicinginstitution boolean,
emergingsmallbusinessflag boolean,
hospitalflag boolean,
contractingofficerbusinesssizedetermination text,
is1862landgrantcollege boolean,
is1890landgrantcollege boolean,
is1994landgrantcollege boolean,
isveterinarycollege boolean,
isveterinaryhospital boolean,
isprivateuniversityorcollege boolean,
isschoolofforestry boolean,
isstatecontrolledinstitutionofhigherlearning boolean,
isserviceprovider boolean,
receivescontracts boolean,
receivesgrants boolean,
receivescontractsandgrants boolean,
isairportauthority boolean,
iscouncilofgovernments boolean,
ishousingauthoritiespublicortribal boolean,
isinterstateentity boolean,
isplanningcommission boolean,
isportauthority boolean,
istransitauthority boolean,
issubchapterscorporation boolean,
islimitedliabilitycorporation boolean,
isforeignownedandlocated boolean,
isarchitectureandengineering boolean,
isdotcertifieddisadvantagedbusinessenterprise boolean,
iscitylocalgovernment boolean,
iscommunitydevelopedcorporationownedfirm boolean,
iscommunitydevelopmentcorporation boolean,
isconstructionfirm boolean,
ismanufacturerofgoods boolean,
iscorporateentitynottaxexempt boolean,
iscountylocalgovernment boolean,
isdomesticshelter boolean,
isfederalgovernmentagency boolean,
isfederallyfundedresearchanddevelopmentcorp boolean,
isforeigngovernment boolean,
isindiantribe boolean,
isintermunicipallocalgovernment boolean,
isinternationalorganization boolean,
islaborsurplusareafirm boolean,
islocalgovernmentowned boolean,
ismunicipalitylocalgovernment boolean,
isnativehawaiianownedorganizationorfirm boolean,
isotherbusinessororganization boolean,
isotherminorityowned boolean,
ispartnershiporlimitedliabilitypartnership boolean,
isschooldistrictlocalgovernment boolean,
issmallagriculturalcooperative boolean,
issoleproprietorship boolean,
istownshiplocalgovernment boolean,
istriballyownedfirm boolean,
istribalcollege boolean,
isalaskannativeownedcorporationorfirm boolean,
iscorporateentitytaxexempt boolean,
iswomenownedsmallbusiness boolean,
isecondisadvwomenownedsmallbusiness boolean,
isjointventurewomenownedsmallbusiness boolean,
isjointventureecondisadvwomenownedsmallbusiness boolean,
walshhealyact text,
servicecontractact text,
davisbaconact text,
clingercohenact text,
otherstatutoryauthority text,
prime_awardee_executive1 text,
prime_awardee_executive1_compensation numeric,
prime_awardee_executive2 text,
prime_awardee_executive2_compensation numeric,
prime_awardee_executive3 text,
prime_awardee_executive3_compensation numeric,
prime_awardee_executive4 text,
prime_awardee_executive4_compensation numeric,
prime_awardee_executive5 text,
prime_awardee_executive5_compensation numeric,
interagencycontractingauthority text,
last_modified_date date
);

--
-- Name base_grants; TYPE: TABLE; Description: keep track of loaded grants
--

CREATE TABLE base_grants(
unique_transaction_id text,
transaction_status text,
fyq int,
cfda_program_num text,
sai_number text,
account_title text,
recipient_name text,
recipient_city_code text,
recipient_city_name text,
recipient_county_code text,
recipient_county_name text,
recipient_zip text,
recipient_type text,
action_type text,
agency_code text,
federal_award_id text,
federal_award_mod text,
fed_funding_amount numeric,
non_fed_funding_amount numeric,
total_funding_amount numeric,
obligation_action_date date,
starting_date date,
ending_date date,
assistance_type text,
record_type text,
correction_late_ind text,
fyq_correction text,
principal_place_code text,
principal_place_state text,
principal_place_cc text,
principal_place_country_code text,
principal_place_zip text,
principal_place_cd text,
cfda_program_title text,
agency_name text,
project_description text,
duns_no text,
duns_conf_code text,
progsrc_agen_code text,
progsrc_acnt_code text,
progsrc_subacnt_code text,
receip_addr1 text,
receip_addr2 text,
receip_addr3 text,
face_loan_guran numeric,
orig_sub_guran numeric,
fiscal_year int,
principal_place_state_code text,
recip_cat_type text,
asst_cat_type text,
recipient_cd text,
maj_agency_cat text,
rec_flag text,
recipient_country_code text,
uri text,
recipient_state_code text,
exec1_fullname text,
exec1_amount numeric,
exec2_fullname text,
exec2_amount numeric,
exec3_fullname text,
exec3_amount numeric,
exec4_fullname text,
exec4_amount numeric,
exec5_fullname text,
exec5_amount numeric,
last_modified_date date
);

--
-- Name base_loans; TYPE: TABLE; Description: keep track of loaded loans
--

CREATE TABLE base_loans(
unique_transaction_id text,
transaction_status text,
fyq int,
cfda_program_num text,
sai_number text,
account_title text,
recipient_name text,
recipient_city_code text,
recipient_city_name text,
recipient_county_code text,
recipient_county_name text,
recipient_zip text,
recipient_type text,
action_type text,
agency_code text,
federal_award_id text,
federal_award_mod text,
fed_funding_amount numeric,
non_fed_funding_amount numeric,
total_funding_amount numeric,
obligation_action_date date,
starting_date date,
ending_date date,
assistance_type text,
record_type text,
correction_late_ind text,
fyq_correction text,
principal_place_code text,
principal_place_state text,
principal_place_cc text,
principal_place_country_code text,
principal_place_zip text,
principal_place_cd text,
cfda_program_title text,
agency_name text,
project_description text,
duns_no text,
duns_conf_code text,
progsrc_agen_code text,
progsrc_acnt_code text,
progsrc_subacnt_code text,
receip_addr1 text,
receip_addr2 text,
receip_addr3 text,
face_loan_guran numeric,
orig_sub_guran numeric,
fiscal_year int,
principal_place_state_code text,
recip_cat_type text,
asst_cat_type text,
recipient_cd text,
maj_agency_cat text,
rec_flag text,
recipient_country_code text,
uri text,
recipient_state_code text,
exec1_fullname text,
exec1_amount numeric,
exec2_fullname text,
exec2_amount numeric,
exec3_fullname text,
exec3_amount numeric,
exec4_fullname text,
exec4_amount numeric,
exec5_fullname text,
exec5_amount numeric,
last_modified_date date
);

--
-- Name base_fin; TYPE: TABLE; Description: keep track of loaded other financial assistance
--

CREATE TABLE base_fin(
unique_transaction_id text,
transaction_status text,
fyq int,
cfda_program_num text,
sai_number text,
account_title text,
recipient_name text,
recipient_city_code text,
recipient_city_name text,
recipient_county_code text,
recipient_county_name text,
recipient_zip text,
recipient_type text,
action_type text,
agency_code text,
federal_award_id text,
federal_award_mod text,
fed_funding_amount numeric,
non_fed_funding_amount numeric,
total_funding_amount numeric,
obligation_action_date date,
starting_date date,
ending_date date,
assistance_type text,
record_type text,
correction_late_ind text,
fyq_correction text,
principal_place_code text,
principal_place_state text,
principal_place_cc text,
principal_place_country_code text,
principal_place_zip text,
principal_place_cd text,
cfda_program_title text,
agency_name text,
project_description text,
duns_no text,
duns_conf_code text,
progsrc_agen_code text,
progsrc_acnt_code text,
progsrc_subacnt_code text,
receip_addr1 text,
receip_addr2 text,
receip_addr3 text,
face_loan_guran numeric,
orig_sub_guran numeric,
fiscal_year int,
principal_place_state_code text,
recip_cat_type text,
asst_cat_type text,
recipient_cd text,
maj_agency_cat text,
rec_flag text,
recipient_country_code text,
uri text,
recipient_state_code text,
exec1_fullname text,
exec1_amount numeric,
exec2_fullname text,
exec2_amount numeric,
exec3_fullname text,
exec3_amount numeric,
exec4_fullname text,
exec4_amount numeric,
exec5_fullname text,
exec5_amount numeric,
last_modified_date date
);

--
-- Data for Name: base_contracts; Type: TABLE DATA
--

COPY base_contracts FROM '/Users/richardbanyi/Developer/Environments/Data/dw/contracts_cleaned.csv'
WITH DELIMITER ',' CSV HEADER QUOTE '"';

-- Data for Name: base_grants; Type: TABLE DATA;
--

COPY base_grants FROM '/Users/richardbanyi/Developer/Environments/Data/dw/grants_cleaned.csv'
WITH DELIMITER ',' CSV HEADER QUOTE '"';

--
-- Data for Name: base_loans; Type: TABLE DATA
--

COPY base_grants FROM '/Users/richardbanyi/Developer/Environments/Data/dw/loans_cleaned.csv'
WITH DELIMITER ',' CSV HEADER QUOTE '"';

--
-- Data for Name: base_fin; Type: TABLE DATA
--

COPY base_grants FROM '/Users/richardbanyi/Developer/Environments/Data/dw/fin_cleaned.csv'
WITH DELIMITER ',' CSV HEADER QUOTE '"';

