--
-- PostgreSQL database load phase
--

CREATE TABLE load_data(
    id SERIAL UNIQUE,
    transaction_id text,
    transaction_status text,
    transaction_cat text,
    transaction_desc text,
    signed_date date,
    award_action_type text,
    award_assistance_type text,
    award_pricing_type text,
    award_id text,
    award_desc text,
    award_descward_amount numeric,
    award_mod text,
    award_mod_reason text,
    agency_cat text,
    agency_name text,
    agency_office_id text,
    funding_bureau_id text,
    funding_bureau_cat text,
    funding_bureau text,
    fuding_bureau_office_id text,
    recipient_name text,
    recipient_legal_name text,
    recipient_streetaddress text,
    recipient_streetaddress2 text,
    recipient_city text,
    recipient_state text,
    recipient_zip text,
    recipient_country text,
    recipient_state_code text,
    recipient_cd text,
    recipient_duns text,
    recipient_parent_name text,
    recipient_parent_duns text,
    recipient_phoneno text,
    recipient_faxno text,
    recipient_registration_date date,
    recipient_organization_type text,
    recipient_num_employees int,
    recipient_annual_revenue numeric,
    product_code text,
    product_claimant_code text,
    product_infotechcommercial text,
    product_plafeofmanufacture text,
    geography_city text,
    geography_state text,
    geography_cd text,
    geography_zip text,
    geography_country text,
    last_modified_date date
);

